# Generated by Django 5.2.3 on 2025-08-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
