# Generated by Django 5.2.3 on 2025-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuarios_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='')),
                ('estructura', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archivos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Tableros',
        ),
    ]
